---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: my_grafana
        imagePullPolicy: Never
        name: grafana
        ports: 
        - containerPort: 3000
          name: grafana-port
        livenessProbe:
           exec:
             command:
             - /bin/ash
             - -c
             - 'pgrep telegraf && pgrep grafana-server'
           initialDelaySeconds: 10
           periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: grafana-port
      protocol: TCP
      port: 3000
      targetPort: 3000